spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5430/order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8080
